//初始化
export const INIT_HEARTRATE = 'INIT_HEARTRATE';
export const INIT_SLEEP = 'INIT_SLEEP';
export const INIT_SPORTS = 'INIT_SPORTS';
//讀取資料
export const LOAD_HEARTRATE = 'LOAD_HEARTRATE';
export const LOAD_SLEEP = 'LOAD_SLEEP';
export const LOAD_SPORTS = 'LOAD_SPORTS';
//讀取設定
export const LOAD_HEARTRATE_SETTING = 'LOAD_HEARTRATE_SETTING';
export const LOAD_SLEEP_SETTING = 'LOAD_SLEEP_SETTING';
export const LOAD_SPORTS_SETTING = 'LOAD_SPORTS_SETTING';
//變更設定
export const UPDATE_HEARTRATE_SETTING = 'UPDATE_HEARTRATE_SETTING';
export const UPDATE_SLEEP_SETTING = 'UPDATE_SLEEP_SETTING';
export const UPDATE_SPORTS_SETTING = 'UPDATE_SPORTS_SETTING';